export const imgUrl = {
    '가야산': require(`../../assets/img/mountainImg/가야산.png`),
    '강천산': require(`../../assets/img/mountainImg/강천산.png`),
    '계룡산': require(`../../assets/img/mountainImg/계룡산.png`),
    '관악산': require(`../../assets/img/mountainImg/관악산.png`),
    '내연산': require(`../../assets/img/mountainImg/내연산.png`),
    '내장산': require(`../../assets/img/mountainImg/내장산.png`),
    '대둔산': require(`../../assets/img/mountainImg/대둔산.png`),
    '덕유산': require(`../../assets/img/mountainImg/덕유산.png`),
    '도봉산': require(`../../assets/img/mountainImg/도봉산.png`),
    '두륜산': require(`../../assets/img/mountainImg/두륜산.png`),
    '두타산': require(`../../assets/img/mountainImg/두타산.png`),
    '마이산': require(`../../assets/img/mountainImg/마이산.png`),
    '북한산': require(`../../assets/img/mountainImg/북한산.png`),
    '산방산': require(`../../assets/img/mountainImg/산방산.png`),
    '설악산': require(`../../assets/img/mountainImg/설악산.png`),
    '성산 일출봉': require(`../../assets/img/mountainImg/성산 일출봉.png`),
    '소백산': require(`../../assets/img/mountainImg/소백산.png`),
    '신불산': require(`../../assets/img/mountainImg/신불산.png`),
    '영주산': require(`../../assets/img/mountainImg/영주산.png`),
    '오대산': require(`../../assets/img/mountainImg/오대산.png`),
    '용눈이오름': require(`../../assets/img/mountainImg/용눈이오름.png`),
    '운악산': require(`../../assets/img/mountainImg/운악산.png`),
    '월악산': require(`../../assets/img/mountainImg/월악산.png`),
    '월출산': require(`../../assets/img/mountainImg/월출산.png`),
    '응봉산': require(`../../assets/img/mountainImg/응봉산.png`),
    '주왕산': require(`../../assets/img/mountainImg/주왕산.png`),
    '지리산': require(`../../assets/img/mountainImg/지리산.png`),
    '칠갑산': require(`../../assets/img/mountainImg/칠갑산.png`),
    '태백산': require(`../../assets/img/mountainImg/태백산.png`),
    '한라산': require(`../../assets/img/mountainImg/한라산.png`),
    '황매산': require(`../../assets/img/mountainImg/황매산.png`),
};